<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Xiaozhi.Core\Xiaozhi.Core.csproj" />
    <ProjectReference Include="..\Xiaozhi.Audio\Xiaozhi.Audio.csproj" />
    <ProjectReference Include="..\Xiaozhi.Protocols\Xiaozhi.Protocols.csproj" />
    <ProjectReference Include="..\Xiaozhi.Mcp\Xiaozhi.Mcp.csproj" />
    <ProjectReference Include="..\Xiaozhi.Plugins\Xiaozhi.Plugins.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
